### ISSUE TITLE
Chrome v64, wtyczka wiesza przeglądarkę

### ISSUE THREAD

**Issue by falqn** [GeoportalPL/ProjectedWMTS#1]
Proszę spróbować otworzyć stronę demo, przeglądarka się wiesza:
https://geoportalpl.github.io/leaflet.projwmts/examples/wmts_services.html
Jest tak od aktualizacji Chrome do v64.

**Comment by GeoportalPL** [comment]
Szanowny Panie,
Na wstępie przepraszamy za takie opóźnienie w odpowiedzi. Obecnie problem nie występuje, Sprawdziliśmy w różnych wersjach Chrome. Gdyby się powtarzał prosimy o kontakt, postaramy się o szybsza weryfikację:) 

Pozdrawiamy 
Zespół BRSiG GUGIK
